steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - '--build-arg'
      - NEXT_PUBLIC_NEST_URL=$$NEXT_PUBLIC_NEST_URL
      - '--build-arg'
      - NEXT_PUBLIC_SLACK_WEBHOOK=$$NEXT_PUBLIC_SLACK_WEBHOOK
      - client/
      - '-f'
      - client/Dockerfile
    id: Build
    secretEnv:
      - NEXT_PUBLIC_NEST_URL
      - NEXT_PUBLIC_SLACK_WEBHOOK
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: page-speed-measurement-nextapp
  _DEPLOY_REGION: asia-northeast1
  _TRIGGER_ID: 9376cc1a-73cc-436b-834c-ad0534cb4fd1
  _AR_HOSTNAME: asia-northeast1-docker.pkg.dev
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - page-speed-measurement-nextapp
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/next_public_nest_url/versions/latest
      env: NEXT_PUBLIC_NEST_URL
    - versionName: projects/$PROJECT_ID/secrets/next_public_slack_webhook/versions/latest
      env: NEXT_PUBLIC_SLACK_WEBHOOK
