version: '3'
services:
  client:
    build: ./docker/client/
    container_name: psi-client
    ports:
      - '9998:3000'
    volumes:
      - ./client:/app
    command: bash
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - default
  app:
    build: ./docker/app
    container_name: psi-app
    ports:
      - '9999:3000'
    volumes:
      - ./app:/app
    tty: true
    logging:
      options:
        max-size: '10m'
        max-file: '5'
  db:
    build: ./docker/mysql/
    env_file:
      - ./client/.env.local
    container_name: psi-mysql
    restart: always
    ports:
      - 3310:3306
    expose:
      - 3310
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: 3310
      TZ: Asia/Tokyo
    volumes:
      # 設定ファイルディレクトリにマウントする
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      # DB初期化ディレクトリにマウントする
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql
      # mysql -u root -p pagespeedinsights < init.sql
    # ネットワーク
    networks:
      - default

# ネットワーク
networks:
  default:
    driver: bridge
