version: '3'
services:
  client:
    build: ./docker/client/
    ports:
      - '9999:3000'
    volumes:
      - ./client:/app
    command: bash
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - '9998:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      # 設定ファイルディレクトリにマウントする
      - ./mysql/conf.d:/etc/mysql/conf.d
      # DB初期化ディレクトリにマウントする
      - ./mysql/init.d:/docker-entrypoint-initdb.d
    # ネットワーク
    networks:
      - default

# ネットワーク
networks:
  default:
    driver: bridge
