import './globals.css'
import Nav from '@/components/Nav'

import { navItems } from '@/components/Nav/NavItems'

export const metadata = {
  title: 'Page Speed Insights Next.js App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <div className='flex'>
          <Nav navItems={navItems} />
          <div className='flex-1 p-4 bg-primary'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
