import './globals.css'
import Nav from '@/components/Nav'

export const metadata = {
  title: 'Page Speed Insights Next.js App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <div className='flex'>
          <Nav />
          <div className='flex-1 p-4'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
