CREATE TABLE site_list_db (
  id INT AUTO_INCREMENT PRIMARY KEY,
  device ENUM('desktop', 'mobile'),
  name VARCHAR(50),
  url VARCHAR(50),
  score INT,
  date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  lcp VARCHAR(10),
  fid VARCHAR(10),
  cls VARCHAR(10),
  fcp VARCHAR(10),
  tbt VARCHAR(10),
  si VARCHAR(10),
);
